[package]
name = "test_4_lint"
version = "0.1.0"
authors = ["macpp <mac.map.void@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
